### PR TITLE
differentiate edit mode and save mode, design action buttons

### PR DESCRIPTION
**Pull request by vishalkrsinghh**
Changes the designs of all actions buttons and differentiate edit mode and save mode

### CODE REVIEW

**Comment by Kritica-rani** [comment]
> Changes the designs of all actions buttons and differentiate edit mode and save mode

Please add the ss of the changes

**Comment by vishalkrsinghh** [comment]
> > Changes the designs of all actions buttons and differentiate edit mode and save mode
> 
> Please add the ss of the changes

I will do it in morning.

**Comment by vishalkrsinghh** [comment]
> > Changes the designs of all actions buttons and differentiate edit mode and save mode
> 
> Please add the ss of the changes

**Comment by vishalkrsinghh** [comment]
> > Changes the designs of all actions buttons and differentiate edit mode and save mode
> 
> Please add the ss of the changes

AddNotesjs
Appcss
Appjs
CreateButtonmodulecss
EditListjs
Headerjs
index
Searchjs
SingleNotesjs

**Comment by vishalkrsinghh** [comment]
> > Changes the designs of all actions buttons and differentiate edit mode and save mode
> 
> Please add the ss of the changes

Output

**Comment by vishalkrsinghh** [comment]
@Kritica-rani
I'm grateful for your outstanding leadership, guidance during the merger. Thank you for inspiring and guiding us. Looking forward to continued success.

**Pull request merged**
